baseURL = "https://generalarcade.github.io/"
languageCode = "en-us"
title = "General Arcade"
publishDir = "public"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3
  [[menu.main]]
    name = "Switch 2 Porting"
    url = "/switch-2-porting/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.main]]
    name = "Contact us"
    url = "#footer"
    weight = 6


disableKinds = []
# Enable sitemap if needed by removing from disableKinds and uncommenting below:
# [sitemap]
#   changefreq = "weekly"
#   filename = "sitemap.xml"
#   priority = 0.5

[taxonomies]
  category = "categories"
  tag = "tags"
  platform = "platforms"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
blog = "/:slug/"
